// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Fescq")>]
[<assembly: AssemblyProductAttribute("Fescq")>]
[<assembly: AssemblyVersionAttribute("0.2.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-02-23T00:00:00.0000000-06:00")>]
[<assembly: AssemblyFileVersionAttribute("0.2.1")>]
[<assembly: AssemblyInformationalVersionAttribute("0.2.1")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","542d596082a9240787da7f85d0c590575cae2248")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fescq"
    let [<Literal>] AssemblyProduct = "Fescq"
    let [<Literal>] AssemblyVersion = "0.2.1"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-02-23T00:00:00.0000000-06:00"
    let [<Literal>] AssemblyFileVersion = "0.2.1"
    let [<Literal>] AssemblyInformationalVersion = "0.2.1"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "542d596082a9240787da7f85d0c590575cae2248"
